### ISSUE TITLE
There are no shader files ( .vert, .frag ) called by the line

### ISSUE THREAD

**Issue by jongdukkim** [ToyMachineGraphics/Vulkan-on-Android#2]
https://github.com/stem-imp/Vulkan-on-Android/blob/9ab9a3e82b534a220a6ed47a361d5b59ebf8ae85/app/src/main/cpp/scene/stereoviewingscene/android/stereo_viewing_scene_renderer_android.cpp#L703

2 files are missing in the path ( https://github.com/stem-imp/Vulkan-on-Android/tree/master/app/src/main/shaders/vr )
AndroidNative::Open<char*>("shaders/vr/texture.vert.spv", app, vertFile);
AndroidNative::Open<char*>("shaders/vr/texture.frag.spv", app, fragFile);

**Comment by willwillmade** [comment]
thanks for your feedback! files uploaded.
